language: node_js
node_js:
  - '15'
sudo: true

branches:
  only:
  - master

script:
  - npm test

jobs:
  include:
    - stage: Api tests
      script: cd server; npm install; npm test; cd ..
    - stage: Deploy server
      script: skip
      before_deploy:
      - cd server
      deploy:
        provider: heroku
        skip_cleanup: true
        api-key: $HEROKU_API_KEY
        app: homecheck-api
      after_deploy:
      - cd ..
    - stage: Deploy client
      script: skip
      before_deploy:
      - cd client/homecheck-vue
      deploy:
        provider: heroku
        skip_cleanup: true
        api-key: $HEROKU_API_KEY
        app: homecheck-vue
      after_deploy:
      - cd ../../