language: node_js
node_js:
- '15'
before_install: cd server
deploy:
  provider: heroku
  api_key:
    secure: fs6klxSi62qpc6DonQsGMumNjOwnvtAWk8RneZ49yMGxSc+/ZPrZAWF/LcAwzBHe7Y7HM/MPXqP94Xkp80x47fqA/khfeTAhh8bSeYStzesnJRiUnj0rRjW2p3zKzXpc+ByQoi89v5TAJ26HC59dSqBitFKZ6cziR7vQ3R7biquknyjhpD2RcGzQXhh2SJgMO+9zGBwDVt/9iUScy4eT7SoAwvDRlTsHdAtBoiZ/Flqk+DGx7NrJKVO2yLN6aizVkCtoFHnanOmG017aIqLNwvIn/vIAZrX8IZOAJoxaaGLc/k/Tl2jEsi3aR75oMfhGYce3WaeOg2rsFB0IRFOpnOPey9RYw5JO7/YSICGk2rR+j+pxi3mj2+D0nyLPm539gZ+Zm8odGevQ11PpHSr7iWbOM/ltXX2roBia52zIFS0OluJbxtiLrv4E+3hkfgQ1jgOlKYIMMa6pIYLu7XbmljSQuBLsmXSagQsaIictngoA1Dhix05NnvSi3ZD82Dk7TkvlCsdzROAK6dkCVX7p2nu3kA/BuUk6aSfDOvBUSGXMI1hKZMJJrqywFQkU9yYQZ0IvS07/YaawpsYfPFQAhLYBrIYsD+dFGMMRpVjAVXNlgyimuX3LaarilARsXghWn1pcsO7Lc+MHcwz0ROD+h/Yv+HXM7/pztGftI77Vqx8=
  app: HomeCheck
  on:
    repo: Momofil31/HomeCheck
  skip_cleanup: 'true'
